name: Go - Continuous Deployment

on:
    push:
        branches:
            - "go/jamesx-cd"
    workflow_dispatch:
        inputs:
            version:
                description: "The release version of GLIDE, formatted as v*.*.* or v*.*.*-rc*"
                required: true
            pkg_go_dev_publish:
                description: "Publish to pkg.go.dev"
                required: true
                type: boolean
                default: false

concurrency:
    group: go-cd-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

permissions:
    id-token: write

jobs:
    load-platform-matrix:
        runs-on: ubuntu-latest
        # environment: AWS_ACTIONS
        outputs:
            PLATFORM_MATRIX: ${{ steps.load-platform-matrix.outputs.PLATFORM_MATRIX }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: load-platform-matrix
              id: load-platform-matrix
              shell: bash
              run: |
                  # Get the matrix from the matrix.json file, without the object that has the IMAGE key
                  export "PLATFORM_MATRIX=$(jq 'map(select(.PACKAGE_MANAGERS | contains(["pkg_go_dev"])))' < .github/json_matrices/build-matrix.json | jq -c .)"
                  echo "PLATFORM_MATRIX=${PLATFORM_MATRIX}" >> $GITHUB_OUTPUT

    validate-release-version:
        runs-on: ubuntu-latest
        outputs:
            RELEASE_VERSION_TAG: ${{ steps.release-tag.outputs.RELEASE_VERSION_TAG }}
        steps:
            - name: Validate Version Agaisnt RegEx
              run: |
                  echo "input version is: ${{ github.event.inputs.version || 'v0.0.7' }}"
                  if ! echo "${{ github.event.inputs.version || 'v0.0.7' }}" | grep -Pq '^v\d+\.\d+\.\d+(-rc\d+)?$'; then
                      echo "Version is not valid, must be v*.*.* or v*.*.*-rc*"
                      exit 1
                  fi

            - name: Checkout for tag check
              uses: actions/checkout@v4

            - name: Validate version agaisnt tags
              run: |
                  git fetch --tags
                  # testing with default value v0.0.7 to procceed to follow up jobs
                  if git tag | grep -q "^go/${{ github.event.inputs.version || 'v0.0.7' }}$"; then
                      echo "Version ${{ github.event.inputs.version || 'v0.0.7' }} already exists."
                      exit 1
                  fi
            - name: Output release tag
              id: release-tag
              run: |
                  echo "RELEASE_VERSION_TAG=go/${{ github.event.inputs.version || 'v0.0.7' }}" >> $GITHUB_OUTPUT

    print_output: # for debug only, needs to be removed
        runs-on: ubuntu-latest
        needs: [load-platform-matrix, validate-release-version]
        if: always()
        steps:
            - name: Echo output
              run: |
                echo "The value of PLATFORM_MATRIX is ${{ needs.load-platform-matrix.outputs.PLATFORM_MATRIX }}"
                echo "The value of RELEASE_VERSION_TAG is ${{ needs.validate-release-version.outputs.RELEASE_VERSION_TAG}}"

    create-binaries-to-publish:
        needs: [load-platform-matrix, validate-release-version]
        # TODO: change repository_owner to 'valkey-io' before merge to upstream
        if: success() && github.repository_owner == 'jamesx-improving'
        strategy:
            fail-fast: false
            matrix:
                host: ${{ fromJson(needs.load-platform-matrix.outputs.PLATFORM_MATRIX)}}
        runs-on: ${{ matrix.host.RUNNER}}
        steps:
            - name: Setup self-hosted runner access
              run: |
                  GHA_HOME=/home/ubuntu/actions-runner/_work/valkey-glide
                  if [ -d $GHA_HOME ]; then
                    sudo chown -R $USER:$USER $GHA_HOME
                    sudo rm -rf $GHA_HOME
                    mkdir -p $GHA_HOME/valkey-glide
                  else
                    echo "No cleaning needed"
                  fi
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
            - name: Install shared software dependencies
              uses: ./.github/workflows/install-shared-dependencies
              with:
                  os: ${{ matrix.host.OS }}
                  target: ${{ matrix.host.TARGET }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
            - name: Set strip flag
              run: |
                if [[ "${{ matrix.host.OS }}" == "macos" ]]; then
                    echo "STRIP_FLAG=-x" >> $GITHUB_ENV
                else
                    echo "STRIP_FLAG=--strip-unneeded" >> $GITHUB_ENV
                fi
            - name: Build Go client
              working-directory: go
              run: |
                  make build
                  strip $STRIP_FLAG target/release/libglide_rs.a
            - name: Upload artifacts
              continue-on-error: true
              uses: actions/upload-artifact@v4
              with:
                  name: go-${{ matrix.host.TARGET }}
                  path: |
                      go/target/release/libglide_rs.a
                      go/lib.h
