name: Go - Continuous Deployment

on:
    push:
        branches:
            - "go/jamesx-cd"
    workflow_dispatch:
        inputs:
            version:
                description: "The release version of GLIDE, formatted as v*.*.* or v*.*.*-rc*"
                required: true
            pkg_go_dev_publish:
                description: "Publish to pkg.go.dev"
                required: true
                type: boolean

concurrency:
    group: go-cd-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

permissions:
    id-token: write

jobs:
    load-platform-matrix:
        runs-on: ubuntu-latest
        # environment: AWS_ACTIONS
        outputs:
            PLATFORM_MATRIX: ${{ steps.load-platform-matrix.outputs.PLATFORM_MATRIX }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: load-platform-matrix
              id: load-platform-matrix
              shell: bash
              run: |
                  # Get the matrix from the matrix.json file, without the object that has the IMAGE key
                  export "PLATFORM_MATRIX=$(jq 'map(select(.PACKAGE_MANAGERS | contains(["pkg_go_dev"])))' < .github/json_matrices/build-matrix.json | jq -c .)"
                  echo "PLATFORM_MATRIX=${PLATFORM_MATRIX}" >> $GITHUB_OUTPUT
